// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puizchlpfcdmqiwyacnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1aXpjaGxwZmNkbXFpd3lhY25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTQ4ODEsImV4cCI6MjA1ODkzMDg4MX0.g7WGZw1m4IM0XBRQlQB16L--NOBQo98S9MvvZvKu5c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);